version: "3.4"

services:
  tacktick-service:
    build: .
    ports:
      - 8080:8080
    # TODO is volume needed?
    volumes:
      - type: bind
        source: ./src/main/resources
        target: /usr/src/app/src/main/resources